version: '3.6'

services:
    agent:
        image: portainer/agent
        container_name: 'agent'
        restart: unless-stopped
        environment:
            AGENT_SECRET: inclua-aqui-a-chave-do-portainer
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/volumes:/var/lib/docker/volumes
            - /:/host
        ports:
            - target: 9001
              published: 9001
              protocol: tcp
              mode: host
    proxy:
        image: 'nginx:1.19.8-alpine'
        container_name: 'proxy'
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443'
        depends_on:
            - app1
            - app2
        volumes:
            - './proxy/nginx:/etc/nginx/conf.d'
            - './asset/dummycert:/etc/dummycert'
            - './proxy/le-challenge-root:/var/www'
            - './asset/letsencrypt:/etc/letsencrypt'              
    php:
        image: 'nexy/php-fpm:8.0.3'
        container_name: 'php'
        restart: unless-stopped
        volumes:
            - './servicos/app1/webroot/:/var/www/webroot/app1'
            - './servicos/app2/webroot/:/var/www/webroot/app2'
            - './php/php.ini:/usr/local/etc/php/php.ini'
    app1:
        image: 'nginx:1.19.8-alpine'
        container_name: 'app1'
        restart: unless-stopped
        volumes:
            - './servicos/app1/nginx.conf:/etc/nginx/conf.d/default.conf'
            - './asset/dummycert:/etc/dummycert'
            - './servicos/app1/webroot/:/var/www/webroot/app1'
        depends_on:
            - php
    app2:
        image: 'openjdk:8-jre-alpine'
        container_name: 'app2'
        restart: unless-stopped
        command: java -Dspring.profiles.active=prod -jar /var/www/webroot/app2/target/app2.jar br.com.servidor.app2.Exemplo
        env_file:
            - 'servicos/app2/.env'
        volumes:
            - './servicos/app2/webroot/:/var/www/webroot/app2'

